l_turkish:
 MR_MUSICAL_TRADITION_RANKING_BUTTON: "M. Geleneği"
 MR_RANKING_BY_MUSICAL_TRADITION: "[concept_elgar_musical_tradition] sıralamasını göster"
 MR_COMPOSER_RANKING_BUTTON: "Besteciler"
 MR_RANKING_BY_COMPOSER: "Dünyadaki tüm [Concept('concept_elgar_composer','$concept_elgar_composers$')] sıralamasını göster."
 COMPOSER_COMPOSER_RANKING_HEADER: "#V [Concept('concept_elgar_composer','$concept_elgar_composers$')] Dünya Sıralaması ([concept_artists_experience])"